import io
from typing import Any

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas


def generate_coo(data: dict[str, Any]) -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    _, height = letter
    y = height - 50
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "USMCA Certificate of Origin (Article 5.2)")
    y -= 30
    c.setFont("Helvetica", 10)
    lines = [
        f"Certifier type: {data.get('certifier_type', '')}",
        f"Certifier name: {data.get('certifier_name', '')}",
        f"Certifier address: {data.get('certifier_address', '')}",
        f"Phone: {data.get('certifier_phone', '')}",
        f"Email: {data.get('certifier_email', '')}",
        f"Exporter: {data.get('exporter_name', '')}",
        f"Exporter address: {data.get('exporter_address', '')}",
        f"Producer: {data.get('producer_name', '')}",
        f"Producer address: {data.get('producer_address', '')}",
        f"Importer: {data.get('importer_name', '')}",
        f"Importer address: {data.get('importer_address', '')}",
        f"Description of goods: {data.get('goods_description', '')}",
        f"HTS classification: {data.get('hts_code', '')}",
        f"Origin criterion (A-D): {data.get('origin_criterion', '')}",
        f"Country of origin: {data.get('country_of_origin', '')}",
        f"Blanket period: {data.get('blanket_period_start', '')} to {data.get('blanket_period_end', '')}",
        f"Authorized signature: {data.get('signature_name', '')}",
        f"Date: {data.get('signature_date', '')}",
        "",
        "Supporting records may include production records, purchase invoices, and bills of materials.",
        "The exporter, producer, or importer may complete this certificate.",
        "TariffIQ generates this form for informational workflow only.",
    ]
    for line in lines:
        c.drawString(50, y, line[:100])
        y -= 14
        if y < 72:
            c.showPage()
            y = height - 50
            c.setFont("Helvetica", 10)
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(
        50,
        50,
        "This document was generated by TariffIQ for informational purposes. "
        "Verify with a licensed customs broker before filing.",
    )
    c.save()
    return buf.getvalue()


def generate_binding_ruling(data: dict[str, Any]) -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    _, height = letter
    y = height - 48
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Binding Ruling Request — Classification (19 CFR 177)")
    y -= 22
    c.setFont("Helvetica", 10)
    c.drawString(
        50,
        y,
        "To: Director, National Commodity Specialist Division, CBP, 201 Varick Street, Suite 501, New York, NY 10014",
    )
    y -= 36
    body = (
        f"Company: {data.get('company_name', '')}\n"
        f"Address: {data.get('company_address', '')}\n"
        f"Contact: {data.get('contact_name', '')} <{data.get('contact_email', '')}>\n\n"
        f"Transaction: {data.get('transaction_description', '')}\n\n"
        f"Product description: {data.get('product_description', '')}\n\n"
        f"Proposed HTS: {data.get('proposed_hts', '')}\n"
        f"GRI applied: {data.get('gri_applied', '')}\n\n"
        f"Legal argument: {data.get('legal_argument', '')}\n\n"
        f"Date: {data.get('date', '')}\n\n"
        "The undersigned requests a binding ruling on classification under the Harmonized Tariff Schedule "
        "of the United States. Supporting drawings, samples, and literature are available upon request.\n"
    )
    text = c.beginText(50, y)
    for para in body.split("\n"):
        text.textLine(para[:115])
    c.drawText(text)
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(
        50,
        56,
        "TariffIQ generated draft — not filed with CBP. Obtain professional review before submission.",
    )
    c.save()
    return buf.getvalue()
